# Generated by Django 4.2.7 on 2023-11-08 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='media/', verbose_name='Изображение'),
        ),
    ]
