# Generated by Django 4.2.7 on 2023-11-08 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_alter_questions_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='image',
        ),
    ]
