# Generated by Django 4.2.7 on 2023-11-08 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_remove_questions_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/guestions/', verbose_name='Изображение'),
        ),
    ]
